# Generated by Django 6.0.1 on 2026-02-04 10:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('juegos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('comentario', models.TextField(validators=[django.core.validators.MinLengthValidator(25), django.core.validators.MaxValueValidator(500)])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='juegos.juego', verbose_name='Juego')),
                ('usuario_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
