# Generated by Django 6.0.1 on 2026-02-04 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_categoria_alter_juego_options_juego_categorias'),
        ('reseñas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha'], 'verbose_name': 'Resena', 'verbose_name_plural': 'Resenas'},
        ),
        migrations.RenameField(
            model_name='resena',
            old_name='usuario_username',
            new_name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='resena',
            unique_together={('juego', 'usuario')},
        ),
    ]
