# Generated by Django 6.0.1 on 2026-02-04 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegos', '0002_categoria_alter_juego_options_juego_categorias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Cuentanos algo sobre ti y tus gustos en videojuegos.', verbose_name='Biografia')),
                ('plataforma', models.CharField(choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series X'), ('SWITCH', 'Nintendo Switch'), ('Múltiples', 'Múltiples plataformas')], default='PC', max_length=20, verbose_name='Plataforma favorita')),
                ('avatar_url', models.URLField(blank=True, help_text='URL de tu imagen de perfil.', verbose_name='Avatar URL')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
